name: ckpool-solo CI

on:
  push:
    branches: [ "solobtc" ]
  pull_request:
    branches: [ "solobtc" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install_packages
      run: sudo apt-get install -y yasm libzmq3-dev
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
