name: ckpool-solo CI/CD

on:
  push:
    branches: [ "solobtc" ]
  pull_request:
    branches: [ "solobtc" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      install_dir: /usr/local/ckpool-solo

    steps:
    - uses: actions/checkout@v3

    - name: install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y yasm libzmq3-dev libcap2-bin

    - name: autogen
      run: ./autogen.sh

    - name: configure
      run: ./configure --prefix=${{ env.install_dir }}

    - name: make
      run: make

    - name: make install
      run: sudo make install

    - uses: actions/upload-artifact@v3
      with:
        name: ckpool-solo_${{ github.sha }}
        path: ${{ env.install_dir }}
